name: aws-quarkus-test
on:
  push:
    branches:
      - "main"
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: action/setup-java@v2
        with:
          java-version: '21'
          distribution:  'corretto'
          cache: 'maven'
      - name: Maven build
        run: mvn -B package --file pom.xml