name: aws-quarkus-test
on: push
permissions:
  id-token: write
  contents: read
env:
  BEANSTALK_APP_NAME: aws-beanstalk-test
  BEANSTALK_ENV_NAME: aws-beanstalk-test-env
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      - name: Maven build
        run: ./mvnw -B package
      - run: mkdir staging && cp target/*.jar staging/${{github.run_id}}.jar
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
  deploy:
    timeout-minutes: 30
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::491085423241:role/GitHubAction-AssumeRoleWithAction
          role-session-name: aws.quarkus.test
      - name: Deploy
        run: |
          aws s3 cp "staging/${{github.run_id}}.jar" s3://my-bucket-edgar8a/quarkus-app-artifact/
          aws elasticbeanstalk create-application-version --application-name $BEANSTALK_APP_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="my-bucket-edgar8a",S3Key="quarkus-app-artifact/${{github.run_id}}.jar"
          aws elasticbeanstalk update-environment --application-name $BEANSTALK_APP_NAME --environment-name $BEANSTALK_ENV_NAME --version-label ${{github.run_id}}
          aws elasticbeanstalk wait environment-updated --application-name $BEANSTALK_APP_NAME --environment-name $BEANSTALK_ENV_NAME
          

